/**
 * @enum {number}
 * @readonly
 */
export const DebugGFXModes = {
    DEBUG_GFX_MODE_NONE: 0,
    DEBUG_GFX_MODE_MINIMUM: 1,
    DEBUG_GFX_MODE_AFFECTS_PERFORMANCE: 2,
    DEBUG_GFX_MODE_VERBOSE: 3,
    DEBUG_GFX_MODE_ALL: 4,
};

/**
 * @enum {number}
 * @readonly
 */
export const RunCommandReturnTypes = {
    RUN_COMMAND_COMMAND_HANDLED: 0,
    RUN_COMMAND_COMMAND_UNHANDLED: 1,
    RUN_COMMAND_COMMAND_WARNING: 2,
    RUN_COMMAND_COMMAND_ERROR: 3,
};

/**
 * @enum {number}
 * @readonly
 */
export const GFXErrorType = {
    GFX_ERROR_TYPE_NONE: 0,
    GFX_ERROR_TYPE_INIT: 1,
    GFX_ERROR_TYPE_OUT_OF_MEMORY_IMAGE: 2,
    GFX_ERROR_TYPE_OUT_OF_MEMORY_BUFFER: 3,
    GFX_ERROR_TYPE_OUT_OF_MEMORY_STAGING: 4,
    GFX_ERROR_TYPE_RENDER_RECORDING: 5,
    GFX_ERROR_TYPE_RENDER_CMD_FAILED: 6,
    GFX_ERROR_TYPE_RENDER_SUBMIT_FAILED: 7,
    GFX_ERROR_TYPE_SWAP_FAILED: 8,
    GFX_ERROR_TYPE_UNKNOWN: 9,
};

/**
 * @enum {number}
 * @readonly
 */
export const GFXWarningType = {
    GFX_WARNING_TYPE_NONE: 0,
    GFX_WARNING_TYPE_INIT_FAILED: 1,
    GFX_WARNING_TYPE_INIT_FAILED_MISSING_INTEGRATED_GPU_DRIVER: 2,
    GFX_WARNING_LOW_ON_MEMORY: 3,
    GFX_WARNING_MISSING_EXTENSION: 4,
    GFX_WARNING_TYPE_UNKNOWN: 5,
};
